
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sales_Inventory.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    public int EmployeeId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Gender { get; set; }

    public System.DateTime DOB { get; set; }

    public string BloodGroup { get; set; }

    public string PermanentAddress { get; set; }

    public string PostalCode { get; set; }

    public string PhoneNo { get; set; }

    public string AlternateNumber { get; set; }

    public string AadharNumber { get; set; }

    public Nullable<System.DateTime> DateofJoining { get; set; }

    public string AccountNo { get; set; }

    public Nullable<int> Salary { get; set; }

    public string Remarks { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

}

}
