//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_Inventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string Purchase_No { get; set; }
        public string Payment_To { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public string Payment_Against { get; set; }
        public string Payment_Type { get; set; }
        public string Payment_Account_No { get; set; }
        public string Payment_Account_Name { get; set; }
        public int Payment_Amount { get; set; }
        public string Payment_Bank { get; set; }
        public string IFSC_Code { get; set; }
        public string Payment_Receiver_Phone { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
